export interface MilitaryConsoleSecurityFlag {
    id: string;
    label: string;
    severity: "low" | "medium" | "high";
    matchCount: number;
    guidance: string;
}

function textValue(value: unknown) {
    if (typeof value === "string") return value;
    if (typeof value === "number" || typeof value === "boolean") return String(value);
    return "";
}

export function visibleEntries(record: Record<string, unknown>) {
    return Object.entries(record).filter(([, value]) => value !== undefined && value !== null && value !== "");
}

export function firstText(record: Record<string, unknown>, keys: string[]) {
    for (const key of keys) {
        const value = textValue(record[key]).trim();
        if (value) return value;
    }

    return "";
}

export function markdownValue(value: unknown): string {
    if (Array.isArray(value)) {
        return value
            .map((item) => {
                if (typeof item === "object" && item !== null) {
                    const nested = visibleEntries(item as Record<string, unknown>)
                        .map(([key, nestedValue]) => `  - ${key}: ${markdownValue(nestedValue).replace(/\n/g, "\n    ")}`)
                        .join("\n");
                    return `- ${nested}`;
                }

                return `- ${String(item)}`;
            })
            .join("\n");
    }

    if (typeof value === "object" && value !== null) {
        return visibleEntries(value as Record<string, unknown>)
            .map(([key, nestedValue]) => `- ${key}: ${markdownValue(nestedValue).replace(/\n/g, "\n  ")}`)
            .join("\n");
    }

    return String(value);
}

export function generatedToMarkdown(
    toolLabel: string,
    generated: Record<string, unknown>,
    flags: MilitaryConsoleSecurityFlag[],
) {
    const parts = [`# ${firstText(generated, ["title"]) || toolLabel}`, "", `Generated by: ${toolLabel}`, ""];

    for (const [key, value] of visibleEntries(generated)) {
        parts.push(`## ${key}`, markdownValue(value), "");
    }

    if (flags.length > 0) {
        parts.push("## Security flags");
        for (const flag of flags) {
            parts.push(`- ${flag.label} (${flag.severity}, ${flag.matchCount}): ${flag.guidance}`);
        }
        parts.push("");
    }

    parts.push("## Reviewer notes", "- Verify facts, sensitive information, and approval path before reuse.");

    return parts.join("\n").trim();
}
