import assert from "node:assert/strict";
import { firstText, generatedToMarkdown, markdownValue, visibleEntries } from "../lib/ai/military-console-format";

const generated = {
    title: "Weekly readiness update",
    summary: "Three tasks completed and one risk needs review.",
    tasks: [
        { owner: "S1", action: "Verify roster", done: true },
        { owner: "S3", action: "Review training note", blockers: ["weather", "range approval"] },
    ],
    empty: "",
};

const markdown = generatedToMarkdown("Weekly report", generated, [
    {
        id: "callsign",
        label: "Call sign",
        severity: "high",
        matchCount: 1,
        guidance: "Remove operational identifiers before sharing.",
    },
]);

assert.equal(firstText(generated, ["missing", "summary"]), generated.summary);
assert.deepEqual(visibleEntries(generated).map(([key]) => key), ["title", "summary", "tasks"]);
assert.match(markdownValue(generated.tasks), /owner: S1/);
assert.match(markdown, /^# Weekly readiness update/);
assert.match(markdown, /Generated by: Weekly report/);
assert.match(markdown, /## tasks/);
assert.match(markdown, /- Call sign \(high, 1\): Remove operational identifiers before sharing\./);
assert.match(markdown, /## Reviewer notes/);

console.log("PASS military console formatting smoke");
